/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpi.sistema.de.carreras.TPI_Carreras;

/**
 *
 * @author maxim
 */
public class MainMenuADM extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenuADM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddRace = new javax.swing.JButton();
        ModifyRace = new javax.swing.JButton();
        DeleteRace = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        AddUser = new javax.swing.JButton();
        ModifyUser = new javax.swing.JButton();
        DeleteUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        LogOut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AddTrack = new javax.swing.JButton();
        ModifyTrack = new javax.swing.JButton();
        DeleteTrack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        AddAdmin = new javax.swing.JButton();
        ModifyAdmin = new javax.swing.JButton();
        DeleteAdmin = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        AddPlace = new javax.swing.JButton();
        ModifyPlace = new javax.swing.JButton();
        DeletePlace = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(28, 33, 53));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Principal de Administrador");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestion de Carreras");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestion de Usuarios");

        AddRace.setBackground(new java.awt.Color(28, 33, 53));
        AddRace.setForeground(new java.awt.Color(255, 255, 255));
        AddRace.setText("Agregar");
        AddRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRaceActionPerformed(evt);
            }
        });

        ModifyRace.setBackground(new java.awt.Color(28, 33, 53));
        ModifyRace.setForeground(new java.awt.Color(255, 255, 255));
        ModifyRace.setText("Modificar");
        ModifyRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyRaceActionPerformed(evt);
            }
        });

        DeleteRace.setBackground(new java.awt.Color(28, 33, 53));
        DeleteRace.setForeground(new java.awt.Color(255, 255, 255));
        DeleteRace.setText("Eliminar");
        DeleteRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRaceActionPerformed(evt);
            }
        });

        jList1.setBackground(new java.awt.Color(52, 62, 103));
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        AddUser.setBackground(new java.awt.Color(28, 33, 53));
        AddUser.setForeground(new java.awt.Color(255, 255, 255));
        AddUser.setText("Agregar");
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });

        ModifyUser.setBackground(new java.awt.Color(28, 33, 53));
        ModifyUser.setForeground(new java.awt.Color(255, 255, 255));
        ModifyUser.setText("Modificar");
        ModifyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyUserActionPerformed(evt);
            }
        });

        DeleteUser.setBackground(new java.awt.Color(28, 33, 53));
        DeleteUser.setForeground(new java.awt.Color(255, 255, 255));
        DeleteUser.setText("Eliminar");
        DeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserActionPerformed(evt);
            }
        });

        jList2.setBackground(new java.awt.Color(52, 62, 103));
        jList2.setForeground(new java.awt.Color(255, 255, 255));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        LogOut.setBackground(new java.awt.Color(28, 33, 53));
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setText("Cerrar Sesion");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gestion  de Circuitos");

        AddTrack.setBackground(new java.awt.Color(28, 33, 53));
        AddTrack.setForeground(new java.awt.Color(255, 255, 255));
        AddTrack.setText("Agregar");
        AddTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTrackActionPerformed(evt);
            }
        });

        ModifyTrack.setBackground(new java.awt.Color(28, 33, 53));
        ModifyTrack.setForeground(new java.awt.Color(255, 255, 255));
        ModifyTrack.setText("Modificar");
        ModifyTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyTrackActionPerformed(evt);
            }
        });

        DeleteTrack.setBackground(new java.awt.Color(28, 33, 53));
        DeleteTrack.setForeground(new java.awt.Color(255, 255, 255));
        DeleteTrack.setText("Eliminar");
        DeleteTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTrackActionPerformed(evt);
            }
        });

        jList3.setBackground(new java.awt.Color(52, 62, 103));
        jList3.setForeground(new java.awt.Color(255, 255, 255));
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gestion de Administradores");

        AddAdmin.setBackground(new java.awt.Color(28, 33, 53));
        AddAdmin.setForeground(new java.awt.Color(255, 255, 255));
        AddAdmin.setText("Agregar");
        AddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAdminActionPerformed(evt);
            }
        });

        ModifyAdmin.setBackground(new java.awt.Color(28, 33, 53));
        ModifyAdmin.setForeground(new java.awt.Color(255, 255, 255));
        ModifyAdmin.setText("Modificar");
        ModifyAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyAdminActionPerformed(evt);
            }
        });

        DeleteAdmin.setBackground(new java.awt.Color(28, 33, 53));
        DeleteAdmin.setForeground(new java.awt.Color(255, 255, 255));
        DeleteAdmin.setText("Eliminar");
        DeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAdminActionPerformed(evt);
            }
        });

        jList4.setBackground(new java.awt.Color(52, 62, 103));
        jList4.setForeground(new java.awt.Color(255, 255, 255));
        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        jList5.setBackground(new java.awt.Color(52, 62, 103));
        jList5.setForeground(new java.awt.Color(255, 255, 255));
        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gestion de Ubicaciones");

        AddPlace.setBackground(new java.awt.Color(28, 33, 53));
        AddPlace.setForeground(new java.awt.Color(255, 255, 255));
        AddPlace.setText("Agregar");
        AddPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlaceActionPerformed(evt);
            }
        });

        ModifyPlace.setBackground(new java.awt.Color(28, 33, 53));
        ModifyPlace.setForeground(new java.awt.Color(255, 255, 255));
        ModifyPlace.setText("Modificar");
        ModifyPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyPlaceActionPerformed(evt);
            }
        });

        DeletePlace.setBackground(new java.awt.Color(28, 33, 53));
        DeletePlace.setForeground(new java.awt.Color(255, 255, 255));
        DeletePlace.setText("Eliminar");
        DeletePlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletePlaceActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Actualizaciones");

        jTextArea1.setBackground(new java.awt.Color(52, 62, 103));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("1.0.3 Se agrego la funcionalidad de Agregar Usuarios y Administradores.\n1.0.2 Se hizo la conexion local con la Base de Datos.\n1.0.1 Se agregaron las IUs Menu Principal, Log In, Menu Principal de \nAdministrador y las IUs de Gestion de Carreras, Usuarios, Administra_\n_dores, Circuitos y Ubicaciones.");
        jScrollPane6.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogOut))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(AddRace)
                                            .addGap(18, 18, 18)
                                            .addComponent(ModifyRace)
                                            .addGap(18, 18, 18)
                                            .addComponent(DeleteRace))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(AddUser)
                                            .addGap(18, 18, 18)
                                            .addComponent(ModifyUser)
                                            .addGap(18, 18, 18)
                                            .addComponent(DeleteUser))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(AddTrack)
                                        .addGap(18, 18, 18)
                                        .addComponent(ModifyTrack)
                                        .addGap(18, 18, 18)
                                        .addComponent(DeleteTrack))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(AddAdmin)
                                        .addGap(18, 18, 18)
                                        .addComponent(ModifyAdmin)
                                        .addGap(18, 18, 18)
                                        .addComponent(DeleteAdmin))
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(AddPlace)
                                        .addGap(18, 18, 18)
                                        .addComponent(ModifyPlace)
                                        .addGap(18, 18, 18)
                                        .addComponent(DeletePlace))
                                    .addComponent(jLabel7))
                                .addGap(0, 138, Short.MAX_VALUE))
                            .addComponent(jScrollPane6))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LogOut))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddRace)
                            .addComponent(ModifyRace)
                            .addComponent(DeleteRace))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddUser)
                    .addComponent(ModifyUser)
                    .addComponent(DeleteUser)
                    .addComponent(AddAdmin)
                    .addComponent(ModifyAdmin)
                    .addComponent(DeleteAdmin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddTrack)
                    .addComponent(ModifyTrack)
                    .addComponent(DeleteTrack)
                    .addComponent(AddPlace)
                    .addComponent(ModifyPlace)
                    .addComponent(DeletePlace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        LogIn log = new LogIn();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogOutActionPerformed
// RACE'S -------------------------------------------------------------------------------------
    private void AddRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRaceActionPerformed
        AddRace a = new AddRace();
        a.setVisible(true);
    }//GEN-LAST:event_AddRaceActionPerformed

    private void ModifyRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyRaceActionPerformed
        ModifyRace r = new ModifyRace();
        r.setVisible(true);
    }//GEN-LAST:event_ModifyRaceActionPerformed

    private void DeleteRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRaceActionPerformed
        DeleteRace r = new DeleteRace();
        r.setVisible(true);
    }//GEN-LAST:event_DeleteRaceActionPerformed
// USER'S -------------------------------------------------------------------------------------
    private void AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserActionPerformed
        AddUser u = new AddUser();
        u.setVisible(true);
    }//GEN-LAST:event_AddUserActionPerformed

    private void ModifyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyUserActionPerformed
        ModifyUser u = new ModifyUser();
        u.setVisible(true);
    }//GEN-LAST:event_ModifyUserActionPerformed

    private void DeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserActionPerformed
        DeleteUser u = new DeleteUser();
        u.setVisible(true);
    }//GEN-LAST:event_DeleteUserActionPerformed
// ADMIN'S -------------------------------------------------------------------------------------
    private void AddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAdminActionPerformed
        AddAdmin a = new AddAdmin();
        a.setVisible(true);
    }//GEN-LAST:event_AddAdminActionPerformed

    private void ModifyAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyAdminActionPerformed
        ModifyAdmin m = new ModifyAdmin();
        m.setVisible(true);
    }//GEN-LAST:event_ModifyAdminActionPerformed

    private void DeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAdminActionPerformed
        DeleteAdmin d = new DeleteAdmin();
        d.setVisible(true);
    }//GEN-LAST:event_DeleteAdminActionPerformed
// TRACK'S -------------------------------------------------------------------------------------
    private void AddTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTrackActionPerformed
        AddTrack a = new AddTrack();
        a.setVisible(true);
    }//GEN-LAST:event_AddTrackActionPerformed

    private void ModifyTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyTrackActionPerformed
        ModifyTrack m = new ModifyTrack();
        m.setVisible(true);
    }//GEN-LAST:event_ModifyTrackActionPerformed

    private void DeleteTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTrackActionPerformed
        DeleteTrack d = new DeleteTrack();
        d.setVisible(true);
    }//GEN-LAST:event_DeleteTrackActionPerformed
// PLACE'S -------------------------------------------------------------------------------------
    private void AddPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlaceActionPerformed
        AddPlace a = new AddPlace();
        a.setVisible(true);
    }//GEN-LAST:event_AddPlaceActionPerformed

    private void ModifyPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyPlaceActionPerformed
        ModifyPlace m = new ModifyPlace();
        m.setVisible(true);
    }//GEN-LAST:event_ModifyPlaceActionPerformed

    private void DeletePlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePlaceActionPerformed
        DeletePlace d = new DeletePlace();
        d.setVisible(true);
    }//GEN-LAST:event_DeletePlaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAdmin;
    private javax.swing.JButton AddPlace;
    private javax.swing.JButton AddRace;
    private javax.swing.JButton AddTrack;
    private javax.swing.JButton AddUser;
    private javax.swing.JButton DeleteAdmin;
    private javax.swing.JButton DeletePlace;
    private javax.swing.JButton DeleteRace;
    private javax.swing.JButton DeleteTrack;
    private javax.swing.JButton DeleteUser;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton ModifyAdmin;
    private javax.swing.JButton ModifyPlace;
    private javax.swing.JButton ModifyRace;
    private javax.swing.JButton ModifyTrack;
    private javax.swing.JButton ModifyUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
